"""
Pydantic data models for Presenta-AI.

These models define the structure of data used throughout the application,
including inputs, intermediate states, and final outputs of the AI review process.
They ensure data consistency and provide type validation.
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AudienceProfile(BaseModel):
    """Defines the characteristics of the target audience for the presentation."""
    role: str = Field(description="The role or position of the audience (e.g., Technical Manager, Investor).")
    interests: str = Field(description="The main interests, concerns, or knowledge level of the audience (e.g., ROI, technical details, market potential).")

class SlideContent(BaseModel):
    """Represents the extracted content from a single slide of the presentation."""
    slide_number: int = Field(description="The sequential number of the slide in the presentation, starting from 1.")
    text: str = Field(description="A summary or key textual content extracted from the slide.")
    title: Optional[str] = Field(default=None, description="The title of the slide, if identifiable.")
    notes: Optional[str] = Field(default=None, description="Speaker notes associated with the slide, if identifiable.")

class DocumentAnalysisResult(BaseModel):
    """Holds the structured analysis results from the DocumentAnalyzerAgent."""
    slides: List[SlideContent] = Field(description="A list of content extracted from each slide.")
    error: Optional[str] = Field(default=None, description="An error message if document analysis failed for any reason.")

class SlideReview(BaseModel):
    """Represents a review for a single slide, typically part of the FinalReport."""
    slide_number: int = Field(description="The slide number to which this review pertains.")
    evaluation: str = Field(description="The synthesized evaluation or critique for this specific slide.")
    suggestion: str = Field(description="Actionable suggestions for improving this specific slide.")

class QnAPair(BaseModel):
    """Represents a single question and its corresponding answer, generated based on the presentation content."""
    question: str = Field(description="An anticipated question that an audience member might ask.")
    answer: str = Field(description="A concise and accurate answer to the anticipated question.")

class FinalReport(BaseModel):
    """
    The comprehensive final report generated by synthesizing all reviews.
    This is the primary output delivered to the user.
    """
    summary_review: str = Field(description="An overall assessment of the presentation, synthesizing all feedback components.")
    storyline_review: str = Field(description="Specific feedback on the presentation's narrative structure, logical flow, and cohesiveness.")
    slide_by_slide_reviews: List[SlideReview] = Field(description="A list of detailed reviews for each slide or logical section of the presentation.")
    qna_list: Optional[List[QnAPair]] = Field(default=None, description="A list of anticipated questions and answers based on the presentation content. May be omitted if Q&A generation is disabled or fails.")

class PresentaAiState(BaseModel):
    """
    Represents the overall state of an ADK session for the Presenta-AI application.
    It tracks initial inputs, intermediate artifacts from agent processing, and final outputs.
    """
    # --- Initial User Inputs ---
    gcs_file_path: str = Field(description="The GCS path to the presentation file to be reviewed.")
    presentation_goal: str = Field(description="The primary goal or objective of the presentation.")
    audience_profile: AudienceProfile = Field(description="The profile of the target audience.")
    selected_configs: Dict[str, str] = Field(description="A dictionary of user-selected configurations for each agent (e.g., {'logic_critic': 'strict'}).")

    # --- Intermediate Agent Outputs (stored as JSON strings or directly as models if parsed) ---
    document_analysis_json_str: Optional[str] = Field(default=None, description="Raw JSON string output from DocumentAnalyzerAgent.")
    document_analysis: Optional[DocumentAnalysisResult] = Field(default=None, description="Parsed DocumentAnalysisResult model.")

    logic_critic_review_text: Optional[str] = Field(default=None, description="Textual output from LogicCriticAgent.")
    audience_persona_review_text: Optional[str] = Field(default=None, description="Textual output from AudiencePersonaAgent.")
    qna_list_json_str: Optional[str] = Field(default=None, description="Raw JSON string output from QnaGeneratorAgent (a list of QnAPairs).")

    # --- Final Report Output ---
    final_report_json_str: Optional[str] = Field(default=None, description="Raw JSON string output from ReportSynthesizerAgent for the FinalReport.")
    final_report: Optional[FinalReport] = Field(default=None, description="Parsed FinalReport model, representing the complete review.")
